name: semantic-release

on: 
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: npm install @semantic-release/github -D
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Get next release version
      id: get-next-version
      run: echo "NEXT_VERSION=$(npx semantic-release --dry-run | grep -i 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/'" >> $GITHUB_ENV

    -
      name: Build and push
      uses: docker/build-push-action@v5
      id: build
      env:
        NEXT_VERSION: ${{ steps.get-next-version.outputs.NEXT_VERSION }}
      with:
        context: .
        push: true
        tags: mtkhanh/hello_world_project:$NEXT_VERSION, mtkhanh/hello_world_project:latest

    - name: Release
      if: steps.build.outcome == 'success'
      run: npx semantic-release -p
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
